# file: nginx-build/tasks/modules/ngx_pagespeed.yml

- name: Nginx Modules - pagespeed - Download the ngx_pagespeed source
  get_url: url={{ nginx_ngx_pagespeed_source }}
                 dest={{ nginx_build_tmp_dir }}
                 mode=0440
  register: nginx_pagespeed_module_dl

- name: Nginx Modules - pagespeed - unpack nginx pagespeed module
  unarchive:  copy=no
              dest={{ nginx_build_tmp_dir }}/
              src={{ nginx_pagespeed_module_dl.dest }}
  when: nginx_pagespeed_module_dl.changed
  register: nginx_pagespeed_module_unpack


- name: Get URL |||||||||||
  shell: |
    psol_url={{ nginx_ngx_pagespeed_psol_source }}
    [ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL)
    wget ${psol_url}
    tar -xzvf $(basename ${psol_url})
  args:
    chdir: "{{ nginx_build_tmp_dir }}/ngx_pagespeed-{{ nginx_ngx_pagespeed_version }}"
  register: output

- name: Display all variables
  debug:
    var: output
    verbosity: 4
#
#- name: Nginx Modules - pagespeed - download pagespeed library
#  get_url: url={{ nginx_ngx_pagespeed_psol_source }}
#            dest={{ nginx_build_tmp_dir }}
#  when: not nginx_psol.stat.exists
#  register: nginx_psol_dl
#
#- name: unpack pagespeed library
#  unarchive: copy=no
#            dest={{ nginx_build_tmp_dir }}/ngx_pagespeed-{{ nginx_pagespeed_version }}-stable/
#            src={{ nginx_psol_dl.dest }}
#  when: nginx_psol_dl.changed
#  register: nginx_psol_unpack